# model_list:
#   - model_name: gpt-4
#     litellm_params:
#       model: openai/gpt-4
#       api_key: "os.environ/OPENAI_API_KEY"
  
#   - model_name: claude-3-opus
#     litellm_params:
#       model: anthropic/claude-3-opus-20240229
#       api_key: "os.environ/ANTHROPIC_API_KEY"

#   - model_name: gemini-pro
#     litellm_params:
#       model: gemini/gemini-pro
#       api_key: "os.environ/GEMINI_API_KEY"

litellm_settings:
  drop_params: true
  set_verbose: false
